[[http]]
name = "influx-relay"
bind-addr = "0.0.0.0:8360"
replicas = 500
default-retention-policy = "autogen"

[http.output]
a = [
        { name="influxdb1", location = "http://192.168.128.105:9122", buffer-size-mb = 8192, max-batch-kb = 500, max-delay-interval = "10s" },
    ]

b = [
        { name="influxdb1", location = "http://192.168.128.105:9122", buffer-size-mb = 8192, max-batch-kb = 500, max-delay-interval = "10s" },
    ]

[http.former]
